# Generated by Django 2.2.1 on 2019-05-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=30, unique=True, verbose_name='手机号码')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('avatar', models.CharField(blank=True, max_length=200, null=True, verbose_name='头像')),
                ('location', models.CharField(max_length=100, verbose_name='坐标')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
