# Generated by Django 2.2.1 on 2019-05-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图片'),
        ),
    ]
